/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseInput: typeof import('./src/components/base-input.vue')['default']
    Box: typeof import('./src/components/box.vue')['default']
    Button: typeof import('primevue/button')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ContentIcon: typeof import('./src/components/Icons/Sidebar/content-icon.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    HomeIcon: typeof import('./src/components/Icons/Sidebar/home-icon.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IntegrationIcon: typeof import('./src/components/Icons/Sidebar/integration-icon.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Password: typeof import('primevue/password')['default']
    PaymentIcon: typeof import('./src/components/Icons/Sidebar/payment-icon.vue')['default']
    Popup: typeof import('./src/components/popup.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsIcon: typeof import('./src/components/Icons/Sidebar/settings-icon.vue')['default']
    SingoutIcon: typeof import('./src/components/Icons/Sidebar/singout-icon.vue')['default']
    TabMenu: typeof import('primevue/tabmenu')['default']
    Textarea: typeof import('primevue/textarea')['default']
    UsersIcon: typeof import('./src/components/Icons/Sidebar/users-icon.vue')['default']
  }
}
