/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Badge: typeof import('primevue/badge')['default']
    BaseInput: typeof import('./src/components/base-input.vue')['default']
    Box: typeof import('./src/components/box.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chips: typeof import('primevue/chips')['default']
    ContentIcon: typeof import('./src/components/Icons/Sidebar/content-icon.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    HomeIcon: typeof import('./src/components/Icons/Sidebar/home-icon.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Integration: typeof import('./src/components/Icons/Sidebar/integration.vue')['default']
    IntegrationIcon: typeof import('./src/components/Icons/Sidebar/integration-icon.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Password: typeof import('primevue/password')['default']
    Payment: typeof import('./src/components/Icons/Sidebar/payment-icon.vue')['default']
    PaymentIcon: typeof import('./src/components/Icons/Sidebar/payment-icon.vue')['default']
    Popup: typeof import('./src/components/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Icons/Sidebar/settings-icon.vue')['default']
    SettingsIcon: typeof import('./src/components/Icons/Sidebar/settings-icon.vue')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    Singout: typeof import('./src/components/Icons/Sidebar/singout-icon.vue')['default']
    SingoutIcon: typeof import('./src/components/Icons/Sidebar/singout-icon.vue')['default']
    Users: typeof import('./src/components/Icons/Sidebar/users-icon.vue')['default']
    UsersIcon: typeof import('./src/components/Icons/Sidebar/users-icon.vue')['default']
  }
}
